version: '3.9'

services:
  node:
    container_name: khoi_server
    build: 
      context: .
      dockerfile: .././docker/Dockerfile
    ports: 
      - "5000:5000"
    volumes:
      - .:/app/src
    command: npm run start
    networks:
      - common
    environment:
      - PORT=5000
      - MONGO_URL=mongodb://mongo/khoi


  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - common


networks:
  common: 
